### ISSUE TITLE
A request has failed extension error

### ISSUE THREAD

**Issue by OrtooJai** [forcedotcom/salesforcedx-vscode-slds#118]
### Summary

When using SLDS Validator, as part of the SFDX VSCode extension pack, it continually fails (about once every minute). This causes the VScode "A request has failed" notification to appear every time.

As far as I can tell the SLDS class validation in LWCs still works despite this.

Unfortunately the "a request has failed" notifications are quite disruptive.

### Error message

> [Error - 15:28:05] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.contentEquals(java.lang.CharSequence)" because the return value of "org.eclipse.lsp4j.Diagnostic.getSource()" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "String.contentEquals(java.lang.CharSequence)" because the return value of "org.eclipse.lsp4j.Diagnostic.getSource()" is null
	at com.salesforce.slds.lsp.codeactions.CodeActionConverter.process(CodeActionConverter.java:241)
	at com.salesforce.slds.lsp.codeactions.CodeActionConverter.lambda$convert$0(CodeActionConverter.java:53)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.salesforce.slds.lsp.codeactions.CodeActionConverter.convert(CodeActionConverter.java:75)
	at com.salesforce.slds.lsp.services.TextDocumentServiceImpl.lambda$codeAction$0(TextDocumentServiceImpl.java:48)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more

### Additional information

<img width="452" alt="Screenshot 2023-07-17 at 15 31 30" src="https://github.com/forcedotcom/salesforcedx-vscode-slds/assets/107479303/e9ee347a-40a3-4ef8-b070-52e8d28c4f4b">

**SLDS Validator Version:** v1.4.8

**VS Code Version**: Version: 1.80.1 (Universal) macOS

**SFDX CLI Version**: sfdx-cli/7.208.10 darwin-x64 node-v18.15.0

**OS and version**: macOS Ventura Version 13.1 (22C65)

**Comment by malex30** [comment]
Did you ever get this resolved? I have a similar issue (i.e. My set up is in Windows)
I'd like to know what this issue was. I've already restarted VS Code, the extension. Not sure what else I can do.

**Comment by MriteshAdak** [comment]
Same question here, I started seeing this error today.
I am on windows but using WSL.

**Comment by OrtooJai** [comment]
Unfortunately I was not able to resolve it. Instead I disabled the SLDS validator extension and have been developing without it.

**Comment by diogosdias** [comment]
The same problem happens to me. I am using "Microsoft Build of OpenJDK with Hotspot 17.0.10+ 7 x64".

![Captura de tela 2024-09-05 125554](https://github.com/user-attachments/assets/ea8cc8cf-9fc4-4368-b4f3-72630760c5c8)

[Error - 12:50:24 PM] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.contentEquals(java.lang.CharSequence)" because the return value of "org.eclipse.lsp4j.Diagnostic.getSource()" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "String.contentEquals(java.lang.CharSequence)" because the return value of "org.eclipse.lsp4j.Diagnostic.getSource()" is null
	at com.salesforce.slds.lsp.codeactions.CodeActionConverter.process(CodeActionConverter.java:241)
	at com.salesforce.slds.lsp.codeactions.CodeActionConverter.lambda$convert$0(CodeActionConverter.java:53)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.salesforce.slds.lsp.codeactions.CodeActionConverter.convert(CodeActionConverter.java:75)
	at com.salesforce.slds.lsp.services.TextDocumentServiceImpl.lambda$codeAction$0(TextDocumentServiceImpl.java:48)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
